name: ci

on:
  push:
    branches: [ master ]
  pull_request:
     branches: [ master ]

jobs:
  build:
    name: Build & Test on ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/gallium", "lts/hydrogen", "current"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
      - run: npm run build --if-present
  lint:
    name: format and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "lts/gallium"
      - run: npm ci
      - run: npm run format
      - run: npm run lint
